storage: ./storage
listen: 0.0.0.0:4873
max_body_size: 10mb
packages:
  '@mx/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
web:
  title: "mx-ui Verdaccio"
